#!/bin/bash

# Import exported vars so the script can work as needed

. tmp

# Some ui stuff
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=30
BACKTITLE="Kernel compiler script"
TITLE=""
MENU="Choose one of the following options:"

OPTIONS=(1 "Compile the rom for selected device"
         2 "Select device only 'lunch $DEVICE' only"
	 3 "Pre add init.nethunter.rc"
         4 "Back"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${OPTIONS[@]}" \
		2>&1 >/dev/tty)

clear
case $CHOICE in
	1)
		echo "Executing brunch for selected device. This can take a while."
		brunch $DEVICE
            ;;
	2)
		lucnh $DEVICE;
		make init.nethunter.rc
		;;
	3)
		lunch $DEVICE;
		;;
        4)
		./starter/scripts/menu
		;;
esac
