#!/bin/bash

# Import exported vars so the script can work as needed

. tmp

# Some ui stuff
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=30
BACKTITLE="Kernel compiler script"
TITLE=""
MENU="Choose one of the following options:"

OPTIONS=(1 "Device compile related tools"
         2 "Source code related tools"
	 3 "Patches for device specific things"
         4 "Exit"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${OPTIONS[@]}" \
		2>&1 >/dev/tty)

clear
case $CHOICE in
	1)
		. $SOURCE/starter/scripts/compile_tools
            ;;
	2)
		. $SOURCE/starter/scripts/source_code_tools
		;;
	3)
		. $SOURCE/starter/scripts/patching_tools
		;;
        4)
		echo "Bye."
		exit 1
		;;
esac
