#!/bin/bash

# Import exported vars so the script can work as needed

. tmp

# Some ui stuff
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=30
BACKTITLE="Kernel compiler script"
TITLE=""
MENU="Choose one of the following options:"

OPTIONS=(1 "Nothing here yet so lemme get u back"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${OPTIONS[@]}" \
		2>&1 >/dev/tty)

clear
case $CHOICE in
	1)
		./starter/scripts/menu
		;;
esac
