#!/bin/bash

# Import exported vars so the script can work as needed

. tmp

# Some ui stuff
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=30
BACKTITLE="Kernel compiler script"
TITLE=""
MENU="Choose one of the following options:"

OPTIONS=(1 "Sync the source code, keeps local commits but in the state as they are."
         2 "Force sync the source code (Erases local commits!!)"
         3 "Back"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
		"${OPTIONS[@]}" \
		2>&1 >/dev/tty)

clear
case $CHOICE in
	1)
		echo "Syncing the source code"
		repo sync
		;;
	2)
		echo "Force syncing the source code"
		repo sync --force-sync
		;;
        3)
		./starter/scripts/menu
		;;
esac
